/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ship.gltf 
Author: Penrolz (https://sketchfab.com/Penrolz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/steampunk-scout-ship-6b6227f7b3884f7fb2deeff6d4ecf489
Title: Steampunk scout ship
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ship.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['steampunk-scout-ship_balloon_0'].geometry} material={materials.balloon} />
            <mesh geometry={nodes['steampunk-scout-ship_balloon_0_1'].geometry} material={materials.balloon} />
            <mesh geometry={nodes['steampunk-scout-ship_ship_0'].geometry} material={materials.ship} />
            <mesh geometry={nodes['steampunk-scout-ship_ship_0_1'].geometry} material={materials.ship} />
            <mesh geometry={nodes['steampunk-scout-ship_ship_0_2'].geometry} material={materials.ship} />
            <mesh geometry={nodes['steampunk-scout-ship_ship_0_3'].geometry} material={materials.ship} />
            <mesh geometry={nodes.propeller_balloon_0.geometry} material={materials.balloon} position={[0.027, 18.529, 17.298]} />
            <mesh geometry={nodes.steering_wheel_ship_0.geometry} material={materials.ship} position={[0.027, 9.216, 4.265]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ship.gltf')
